=== mapsforge/vtm/resources/rendertheme.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:tns="http://opensciencemap.org/rendertheme"
    xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://opensciencemap.org/rendertheme" xml:lang="en">
    <!-- attribute types -->
    <xs:simpleType name="cap">
        <xs:restriction base="xs:string">
            <xs:enumeration value="butt" />
            <xs:enumeration value="round" />
            <xs:enumeration value="square" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="closed">
        <xs:restriction base="xs:string">
            <xs:enumeration value="yes" />
            <xs:enumeration value="no" />
            <xs:enumeration value="any" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="color">
        <xs:restriction base="xs:string">
            <xs:pattern value="#([0-9a-fA-F]{6}|[0-9a-fA-F]{8})" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="elementList">
        <xs:restriction base="xs:string">
            <xs:enumeration value="node" />
            <xs:enumeration value="way" />
            <xs:enumeration value="any" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="selectorList">
        <xs:restriction base="xs:string">
            <xs:enumeration value="first" />
            <xs:enumeration value="any" />
            <xs:enumeration value="when-matched" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="fontFamily">
        <xs:restriction base="xs:string">
            <xs:enumeration value="default" />
            <xs:enumeration value="default_bold" />
            <xs:enumeration value="monospace" />
            <xs:enumeration value="sans_serif" />
            <xs:enumeration value="serif" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="fontStyle">
        <xs:restriction base="xs:string">
            <xs:enumeration value="bold" />
            <xs:enumeration value="bold_italic" />
            <xs:enumeration value="italic" />
            <xs:enumeration value="normal" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="nonNegativeFloat">
        <xs:restriction base="xs:float">
            <xs:minInclusive value="0" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="src">
        <xs:restriction base="xs:string">
            <!-- <xs:pattern value="(jar|file)\:.+" /> -->
            <xs:pattern value=".+" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="strokeDasharray">
        <xs:restriction base="xs:string">
            <xs:pattern
                value="([0-9]+(\.[0-9]+)? *, *[0-9]+(\.[0-9]+)? *, *)*[0-9]+(\.[0-9]+)? *, *[0-9]+(\.[0-9]+)?" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="textKey">
        <xs:restriction base="xs:string">
            <xs:enumeration value="ele" />
            <xs:enumeration value="addr:housenumber" />
            <xs:enumeration value="name" />
            <xs:enumeration value="ref" />
        </xs:restriction>
    </xs:simpleType>

    <!-- rendering instructions -->
    <xs:complexType name="area">
        <xs:attribute name="id" default="0" type="xs:string" use="optional" />
        <xs:attribute name="use" default="0" type="xs:string" use="optional" />
        <xs:attribute name="src" type="tns:src" use="optional" />
        <xs:attribute name="fill" default="#000000" type="tns:color" use="optional" />
        <xs:attribute name="stroke" default="#00000000" type="tns:color" use="optional" />
        <xs:attribute name="stroke-width" default="0" type="tns:nonNegativeFloat" use="optional" />
        <xs:attribute name="fade" default="-1" type="xs:integer" use="optional" />
        <xs:attribute name="blend" default="-1" type="xs:integer" use="optional" />
        <xs:attribute name="blend-fill" default="#000000" type="tns:color" use="optional" />
        <xs:attribute name="mesh" default="false" type="xs:boolean" use="optional" />
    </xs:complexType>

    <xs:complexType name="caption">
        <xs:attribute name="k" type="tns:textKey" use="required" />
        <xs:attribute name="dy" default="0" type="xs:float" use="optional" />
        <xs:attribute name="font-family" default="default" type="tns:fontFamily" use="optional" />
        <xs:attribute name="style" default="normal" type="tns:fontStyle" use="optional" />
        <xs:attribute name="size" default="0" type="tns:nonNegativeFloat" use="optional" />
        <xs:attribute name="fill" default="#000000" type="tns:color" use="optional" />
        <xs:attribute name="stroke" default="#000000" type="tns:color" use="optional" />
        <xs:attribute name="stroke-width" default="0" type="tns:nonNegativeFloat" use="optional" />
        <!-- priority for label placement, 0 = highest priority -->
        <xs:attribute name="priority" default="0" type="xs:integer" use="optional" />

        <!-- symbol src name in atlas -->
        <xs:attribute name="symbol" type="tns:src" use="optional" />
    </xs:complexType>

    <xs:complexType name="circle">
        <xs:attribute name="radius" type="tns:nonNegativeFloat" use="required" />
        <xs:attribute name="scale-radius" default="false" type="xs:boolean" use="optional" />
        <xs:attribute name="fill" default="#00000000" type="tns:color" use="optional" />
        <xs:attribute name="stroke" default="#00000000" type="tns:color" use="optional" />
        <xs:attribute name="stroke-width" default="0" type="tns:nonNegativeFloat" use="optional" />
    </xs:complexType>

    <xs:complexType name="line">
        <!-- style: TODO only in style-line-->
        <xs:attribute name="id" default="0" type="xs:string" use="optional" />

        <!-- inherited style -->
        <xs:attribute name="use" default="0" type="xs:string" use="optional" />

        <xs:attribute name="src" type="tns:src" use="optional" />
        <xs:attribute name="stroke" default="#000000" type="tns:color" use="optional" />
        <xs:attribute name="width" default="0" type="xs:float" use="optional" />
        <!-- minimum scaled width to draw outline -->
        <xs:attribute name="min" default="0" type="xs:float" use="optional" />
        <xs:attribute name="dasharray" type="tns:strokeDasharray" use="optional" />
        <xs:attribute name="cap" default="round" type="tns:cap" use="optional" />
        <xs:attribute name="outline" default="" type="xs:string" use="optional" />
        <xs:attribute name="fade" default="-1" type="xs:integer" use="optional" />
        <xs:attribute name="blur" default="-1" type="xs:float" use="optional" />
        <xs:attribute name="fix" default="false" type="xs:boolean" use="optional" />

        <!-- stipple repeat in 'pixel' -->
        <xs:attribute name="stipple" default="0" type="xs:integer" use="optional" />
        <!-- stipple color -->
        <xs:attribute name="stipple-stroke" default="#000000" type="tns:color" use="optional" />
        <!-- stipple width relative to line width, i.e 0.0-1.0 -->
        <xs:attribute name="stipple-width" default="0" type="xs:float" use="optional" />

    </xs:complexType>

    <!-- <xs:complexType name="outline">
      <xs:attribute name="name" type="xs:string" use="optional"
      default="0" />
      <xs:attribute name="src" type="tns:src" use="optional" />
      <xs:attribute name="stroke" type="tns:color" use="optional"
      default="#000000" />
      <xs:attribute name="stroke-width" type="tns:nonNegativeFloat"
      use="optional" default="0" />
      </xs:complexType>
    -->
    <xs:complexType name="lineSymbol">
        <xs:attribute name="src" type="tns:src" use="required" />
        <xs:attribute name="align-center" default="false" type="xs:boolean" use="optional" />
        <xs:attribute name="repeat" default="false" type="xs:boolean" use="optional" />
    </xs:complexType>

    <xs:complexType name="text">
        <xs:attribute name="id" default="0" type="xs:string" use="optional" />
        <xs:attribute name="use" default="0" type="xs:string" use="optional" />

        <xs:attribute name="k" default="name" type="tns:textKey" use="optional" />
        <xs:attribute name="dy" default="0" type="xs:float" use="optional" />
        <xs:attribute name="font-family" default="default" type="tns:fontFamily" use="optional" />
        <xs:attribute name="style" default="normal" type="tns:fontStyle" use="optional" />
        <xs:attribute name="size" default="0" type="tns:nonNegativeFloat" use="optional" />
        <xs:attribute name="fill" default="#000000" type="tns:color" use="optional" />
        <xs:attribute name="stroke" default="#000000" type="tns:color" use="optional" />
        <xs:attribute name="stroke-width" default="0" type="tns:nonNegativeFloat" use="optional" />
        <xs:attribute name="caption" default="false" type="xs:boolean" use="optional" />
        <!-- priority for label placement, 0 = highest priority -->
        <xs:attribute name="priority" default="0" type="xs:integer" use="optional" />
    </xs:complexType>

    <xs:complexType name="symbol">
        <xs:attribute name="src" type="tns:src" use="required" />
    </xs:complexType>

    <xs:complexType name="extrusion">
        <xs:attribute name="line-color" type="tns:color" use="optional" />
        <xs:attribute name="side-color" type="tns:color" use="required" />
        <xs:attribute name="top-color" type="tns:color" use="required" />
    </xs:complexType>


    <!-- match elements -->
    <xs:complexType name="m">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
            <!-- recursion to allow for nested m -->
            <xs:element name="m" type="tns:m" />

            <xs:element name="area" type="tns:area" />
            <xs:element name="caption" type="tns:caption" />
            <xs:element name="circle" type="tns:circle" />
            <xs:element name="line" type="tns:line" />
            <xs:element name="outline" type="tns:line" />
            <xs:element name="lineSymbol" type="tns:lineSymbol" />
            <xs:element name="text" type="tns:text" />
            <xs:element name="extrusion" type="tns:extrusion" />
            <xs:element name="symbol" type="tns:symbol" />

            <!-- outline is defined within rules to match layering -->
            <xs:element name="outline-layer" type="tns:line" />
        </xs:choice>

        <xs:attribute name="select" default="any" type="tns:selectorList" use="optional" />
        <xs:attribute name="e" type="tns:elementList" use="optional" />
        <xs:attribute name="k" type="xs:string" use="optional" />
        <xs:attribute name="v" type="xs:string" use="optional" />
        <xs:attribute name="closed" default="any" type="tns:closed" use="optional" />
        <xs:attribute name="zoom-min" default="0" type="xs:unsignedByte" use="optional" />
        <xs:attribute name="zoom-max" default="127" type="xs:unsignedByte" use="optional" />

    </xs:complexType>

    <xs:complexType name="atlasRect">
        <xs:attribute name="id" type="xs:string" use="required" />
        <xs:attribute name="pos" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="atlas">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element name="rect" type="tns:atlasRect" />
        </xs:choice>
        <xs:attribute name="img" type="xs:string" use="required" />
    </xs:complexType>

    <!-- rendertheme element -->
    <xs:complexType name="rendertheme">
        <xs:sequence maxOccurs="1" minOccurs="0">

            <!-- style definitions -->
            <xs:sequence maxOccurs="256" minOccurs="0">
                <xs:choice maxOccurs="unbounded" minOccurs="0">
                    <xs:element name="style-text" type="tns:text" />
                    <xs:element name="style-area" type="tns:area" />
                    <xs:element name="style-line" type="tns:line" />
                    <!-- <xs:element name="style-outline" type="tns:line" /> -->
                </xs:choice>
            </xs:sequence>

            <xs:choice maxOccurs="1" minOccurs="0">
                <xs:element name="atlas" type="tns:atlas" />
            </xs:choice>

            <!-- matching rules -->
            <xs:sequence maxOccurs="unbounded" minOccurs="0">
                <xs:element name="m" type="tns:m" />
            </xs:sequence>
        </xs:sequence>
        <xs:attribute name="version" type="xs:positiveInteger" use="required" />
        <xs:attribute name="map-background" default="#ffffff" type="tns:color" use="optional" />
        <xs:attribute name="base-stroke-width" default="1" type="tns:nonNegativeFloat"
            use="optional" />
        <xs:attribute name="base-text-scale" default="1" type="tns:nonNegativeFloat"
            use="optional" />
    </xs:complexType>


    <!-- root element -->
    <xs:element name="rendertheme" type="tns:rendertheme" />
</xs:schema>

=== mapsforge/vtm/vtm-playground/resources/assets/styles/mapzen.xml
<rendertheme xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" map-background="#e8ecd3"
    version="1" xmlns="http://opensciencemap.org/rendertheme"
    xsi:schemaLocation="http://opensciencemap.org/rendertheme ../../rendertheme.xsd">
    <!-- icons 32 -->
    <atlas img="icons/poi_icons_32.png">
        <rect id="1_airport" pos="0 0 32 32" />
        <rect id="2_taxi " pos="0 37 32 32" />
        <rect id="3_train" pos="0 74 32 32" />
        <rect id="4_boat" pos="0 111 32 32" />
        <rect id="5_bus" pos="0 148 32 32" />
        <rect id="6_park" pos="0 185 32 32" />
        <rect id="7_gas_station" pos="0 222 32 32" />
        <rect id="8_hotel" pos="0 259 32 32" />
        <rect id="9_bank" pos="0 296 32 32" />
        <rect id="10_library" pos="0 333 32 32" />
        <rect id="11_school" pos="0 370 32 32" />
        <rect id="12_post_office" pos="0 407 32 32" />
        <rect id="13_hospital" pos="0 444 32 32" />
        <rect id="14_pharmacy" pos="0 481 32 32" />
        <rect id="15_museum" pos="0 518 32 32" />
        <rect id="16_building" pos="0 555 32 32" />
        <rect id="17_movie_theatre" pos="0 592 32 32" />
        <rect id="18_spiritual_center" pos="0 629 32 32" />
        <rect id="19_temple" pos="0 629 32 32" />
        <rect id="20_church" pos="0 666 32 32" />
        <rect id="21_toilet" pos="0 703 32 32" />
        <rect id="22_restaurant" pos="0 777 32 32" />
        <rect id="23_cafe" pos="0 814 32 32" />
        <rect id="24_coffee_shop" pos="0 851 32 32" />
        <rect id="25_bar" pos="0 888 32 32" />
        <rect id="26_sports" pos="0 925 32 32" />
        <rect id="27_soccer" pos="0 962 32 32" />
        <rect id="28_baseball" pos="0 999 32 32" />
        <rect id="29_basketball" pos="0 1036 32 32" />
        <rect id="30_parking" pos="0 1073 32 32" />
        <rect id="31_information" pos="0 1110 32 32" />
    </atlas>

    <style-line id="trunk" stroke="#ebf0d8" width="1.5" />
    <style-line cap="round" id="motorway" priority="0" stroke="#C99272" width="2.25" />
    <style-line cap="butt" id="primary" priority="1" stroke="#f3f7ef" width="2" />
    <style-line cap="butt" id="secondary" priority="2" stroke="#f3f7e6" width="1.75" />
    <style-line cap="butt" id="tertiary" priority="3" stroke="#f3f7e6" width="1" />
    <style-line cap="butt" faded="7" id="motorway:z7" priority="0" stroke="#C99272" width="1.25" />
    <style-line cap="butt" fix="true" id="fix" width="1.0" />

    <style-line cap="butt" id="park-line" stroke="#94af89" width="0.2" />
    <style-line cap="butt" id="park-2-line" stroke="#9ca070" width="0.2" />

    <style-text fill="#294d6b" id="water-label-sm" k="name" size="18" stroke-width="0.5" />
    <style-text fill="#294d6b" id="water-label-md" k="name" size="24" stroke-width="1.0" />
    <style-text fill="#294d6b" id="water-label-lg" k="name" size="28" stroke-width="1.25" />
    <style-text fill="#42513a" id="park-label" k="name" size="21" stroke="#e8ecd3"
        stroke-width="0.5" />

    <style-text fill="#666666" id="street-label-sm" k="name" priority="3" size="18" stroke="#e4e9cc"
        stroke-width="1.0" />
    <style-text fill="#666666" id="street-label-md" k="name" priority="3" size="24" stroke="#e4e9cc"
        stroke-width="2.0" />
    <style-text style="bold" character-spacing="0.3" fill="#666666" id="street-label-b" k="name"
        priority="2" size="21" stroke="#e4e9cc" stroke-width="1.0" />
    <style-text fill="#666666" id="street-label-lg" k="name" priority="1" size="28" stroke="#e4e9cc"
        stroke-width="2.0" />
    <style-text style="bold" character-spacing="0.3" fill="#666666" id="street-label-lg-b" k="name"
        priority="1" size="28" stroke="#e4e9cc" stroke-width="2.0" />
    <style-text style="italic" fill="#666666" id="street-label-sm-i" k="name" priority="3" size="18"
        stroke="#e4e9cc" stroke-width="1.0" />

    <!--     <style-text id="poi-label" k="name" size="16" fill="#000000" stroke="#e8ecd3" stroke-width="0.5" dy="2" dx="2" text-align="center" /> -->
    <style-area fill="#afcfa2" id="park" />
    <style-area id="park-2" src="patterns/park_texture_2.png" />

    <!-- ways -->
    <m e="way">
        <!-- parks, playgrounds + labels -->
        <m select="first">
            <m fade="9" v="military">
                <area use="park-2" />
                <line use="park-line-2" />
            </m>
            <m fade="9" k="kind" v="residential|farmyard">
                <area use="park" />
                <line use="park-line" />
            </m>
            <m v="retail">
                <area fill="#ebf0d8" stroke="#ebf0d8" stroke-width="0.2" />
            </m>
            <m v="industrial|brownfield|railway">
                <area fill="#ebf0d8" stroke="#dcdbb3" stroke-width="0.2" />
            </m>
            <m v="commercial">
                <area fill="#ebf0d8" stroke="#ebf0d8" stroke-width="0.2" />
            </m>
            <m v="construction|greenfield">
                <area fill="#e8ecd3" stroke="#ebf0d8" stroke-width="0.2" />
            </m>
            <m v="garages">
                <area fill="#d6d6e4" />
            </m>
            <m v="landfill|quarry">
                <area fill="#ebf0d8" stroke="#d4d8c0" stroke-width="0.2" />
            </m>
            <m fade="9" v="cemetery">
                <area use="park" />
                <line use="park-line" />
            </m>
            <m fade="9" v="field|farm|farmland|meadow|grass">
                <area use="park" />
                <line use="park-line" />
            </m>
            <m fade="9" v="allotments|village_green|recreation_ground">
                <area use="park-2" />
                <line use="park-line-2" />
            </m>
            <m v="reservoir|basin">
                <area fill="#8db3b6" stroke="#6F9D9E" stroke-width="0.2" />
            </m>
        </m>
        <m k="name" zoom-min="18">
            <text use="park-label" />
        </m>

        <m k="kind" v="forest|wood|scrub">
            <m fade="9" k="kind" v="coniferous|deciduous|mixed">
                <area use="park" />
                <line use="park-line" />
            </m>
            <m fade="9" k="kind" v="wood">
                <area use="park" />
            </m>
            <m zoom-min="15">
                <text use="park-label" />
            </m>
        </m>

        <!-- amenity -->
        <m k="amenity">
            <m select="first">
                <m v="kindergarten|school|college|university">
                    <area fill="#ebf0d8" stroke="#d4d8c0" stroke-width="0.2" />
                </m>
                <m fade="9" v="grave_yard">
                    <area use="park" />
                    <line use="park-line" />
                </m>
                <m v="parking">
                    <area fill="#ebf0d8" stroke="#d4d8c0" stroke-width="0.2" />
                    <m k="access" v="private" zoom-min="15">
                        <area fill="#ebf0d8" stroke="#d4d8c0" stroke-width="0.2" />
                    </m>
                </m>
                <m closed="yes" v="fountain">
                    <area fill="#8db3b6" stroke="#6F9D9E" stroke-width="0.15" />
                </m>
                <m v="hospital" zoom-min="16">
                    <!-- <symbol src="13_hospital" /> -->
                </m>
                <m v="theatre" zoom-min="16">
                    <!-- <symbol src="17_movie_theatre" /> -->
                </m>
                <m v="toilets" zoom-min="16">
                    <!-- <symbol src="21_toilet" /> -->
                </m>
            </m>
        </m>

        <!-- natural -->
        <m select="first">
            <m v="coastline">
                <m closed="no">
                    <line cap="butt" fix="true" stroke="#708599" width="2.0" />
                </m>
                <m closed="yes">
                    <area fill="#8db3b6" stroke="#6F9D9E" stroke-width="0.4" />
                </m>
            </m>
        </m>
        <m zoom-min="10">
            <m v="glacier">
                <area fill="#8db3b6" stroke="#6F9D9E" stroke-width="0.8" />
            </m>
            <m v="land">
                <area fill="#f8f8f8" stroke="#e0e0e0" stroke-width="0.1" />
            </m>
            <m v="beach">
                <area fill="#eecc55" />
            </m>
            <m v="heath">
                <area fill="#ebf0d8" stroke="#ffff90" stroke-width="0.2" />
            </m>
            <m v="marsh|wetland">
                <area fill="#8db3b6" />
            </m>
            <m k="name" zoom-min="16">
                <text use="water-label" />
            </m>
        </m>

        <!-- leisure -->
        <m k="kind">
            <!-- park labels -->
            <m fade="9" v="park|park or protected land|garden">
                <area use="park" />
                <m zoom-min="11">
                    <line cap="butt" stroke="#94af89" width="0.3" />
                </m>
                <m zoom-min="15">
                    <text use="park-label" />
                </m>
            </m>
            <m fade="9" v="golf_course|common|green">
                <area use="park-2" />
                <m zoom-min="11">
                    <line cap="butt" stroke="#9ca070" width="0.3" />
                </m>
                <m zoom-min="15">
                    <text use="park-label" />
                </m>
            </m>
            <m fade="9" v="playground|playing_fields|pitch|dog_park">
                <m zoom-min="13">
                    <area use="park" />
                </m>
                <m zoom-min="17">
                    <line cap="butt" stroke="#94af89" width="0.3" />
                    <text use="park-label" />
                </m>
            </m>
            <m fade="9" v="stadium">
                <area use="park-2" />
                <line use="park-line-2" />
                <m zoom-min="15">
                    <text use="park-label" />
                </m>
